version: "3.9"

services:
  console:
    build:
      context: .
      dockerfile: Dockerfile.console
    container_name: console_app
    tty: true  # позволяет видеть вывод
    stdin_open: true

  sportapi:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fastapi_app
    ports:
      - "8000:8000"


