services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn sports_api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/usr/src/app/data
