openapi: 3.0.3
info:
  title: Sports Stats API
  version: 1.0.0
  description: |
    API для получения статистики спортивных команд и игроков. 
    Поддерживает запросы статистики команд, сравнение игроков, получение голов и отображение веб-интерфейса.
servers:
  - url: http://127.0.0.1
    description: Локальный сервер

paths:
  /stats:
    get:
      summary: Получить статистику команды
      parameters:
        - name: team_name
          in: query
          required: true
          schema:
            type: string
          description: Название команды
      responses:
        '200':
          description: Успешный ответ со статистикой команды
          content:
            application/json:
              schema:
                type: object
                properties:
                  wins:
                    type: integer
                    description: Количество побед
                  loses:
                    type: integer
                    description: Количество поражений
                  dif:
                    type: integer
                    description: Разница голов (забито - пропущено)
                example:
                  wins: 10
                  loses: 3
                  dif: 15

  /versus:
    get:
      summary: Сравнение двух игроков
      parameters:
        - name: player1_id
          in: query
          required: true
          schema:
            type: integer
        - name: player2_id
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Количество матчей, в которых игроки играли друг против друга
          content:
            application/json:
              schema:
                type: object
                properties:
                  cnt:
                    type: integer
                    description: Количество матчей
                example:
                  cnt: 7

  /goals:
    get:
      summary: Получить голы игрока
      parameters:
        - name: player_id
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Список голов игрока
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    match:
                      type: integer
                      description: ID матча
                    time:
                      type: integer
                      description: Минута, на которой забит гол
                example:
                  - match: 12
                    time: 34
                  - match: 15
                    time: 78

  /front/stats:
    get:
      summary: Веб-страница со статистикой команд
      responses:
        '200':
          description: HTML страница с информацией по статистике команд
          content:
            text/html:
              schema:
                type: string

  /front/versus:
    get:
      summary: Веб-страница сравнения игроков
      responses:
        '200':
          description: HTML страница для сравнения игроков
          content:
            text/html:
              schema:
                type: string

components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
